# Site settings
title: Future Smart Thermostat Study
email: chuanche@umich.edu
url: https://sprite728.github.io
description: "The recruitment website for the future smart thermostat study conducted by University of Michigan."
baseurl: "/sauna-studysite"
# Color settings


color:
  primary-dark: '#000000'
  dark-purple: ''
  links: '#219ab3'

# Footer settings
footer: "University of Michigan, Interaction Ecologies Group"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
